---
- name: Install Docker and Deploy Image
  hosts: vms
  become: yes
  tasks:
    - name: Install required packages
      yum:
        name:
          - docker
        state: present
        update_cache: yes

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker image from Docker Hub
      docker_image:
        name: "youssefmoghazy/python-app-image:latest"
        source: pull

    - name: Run Docker container
      docker_container:
        name: weather_app
        image: "youssefmoghazy/python-app-image:latest"
        state: started
        restart_policy: always
